config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root to: "books#index"

resources :books do
  resources :reviews
end

end

app/models/book.rb
class Book < ActiveRecord::Base

has_many :reviews, dependent: :destroy
belongs_to :user

validates :title, length: { minimum: 2 }
validates :description, length: { minimum: 50 }
validates :url, presence: true
validates :url, :format => URI::regexp(%w(http https))
end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :book
  belongs_to :user

  validates :review, length: { minimum: 50 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books
  has_many :reviews
  
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true
    validates_format_of :email, :with => /@/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name, :role, :email, :password]
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!, only: [:destroy, :delete, :new, :create, :edit, :update]

  def index
    @books = Book.all.order(created_at: :desc)
    @user = User.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to root_path, :notice => "Book was successfully created"
    else
      render :new
    end
  end

  def show
    id = params[:id]
    @book = Book.find(id)
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    if @book.destroy
      redirect_to root_path, notice: "Book was successfully deleted"
    else
      render :edit, notice: "Book was not deleted"
    end
  end

private
  def book_params
    params.require(:book).permit(:title, :author, :description, :url, :user_id, :id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticate_user!, only: [:destroy, :delete, :new, :create, :edit, :update]


  def new
    @book = Book.find(params[:book_id])
    @review = Review.new
  end

  def show
    @review = Review.find(params[:id])
  end

  def create
    @book = Book.find(params[:book_id])
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.book_id = @book.id

    if @review.save
      redirect_to root_path, notice: "Review was successfully created"
    else
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_params)

    if @review.update_attributes(review_params)
      redirect_to root_path, notice: "Review was successfully edited"
    else
      render :edit, notice: "Review did not update"
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    if @review.destroy
      redirect_to root_path, notice: "Review was successfully deleted"
    else
      render :edit, notice: "Review was not deleted"
    end
  end

private
  def review_params
    params.require(:review).permit(:review, :book_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
<a href="<%= new_book_path %>">Add a book</a>

<% @books.each do |book| %>

<ul>
  <li><a href="/books/<%=book.id %>"><%= book.title %></a></li>
  <li><%= book.author %></li>
  <li><%= book.description %></li>
  <li><%= book.url %></li>
  <li><%= book.user.role %></li>
</ul>
<% end %>

app/views/books/new.html.erb
<%= form_for(@book) do |f| %>

  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= "#{@book.errors.count} prevented the book from being saved:" %></h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
  <%= f.label :title, "Title" %><br />
  <%= f.text_field :title %>
</div>

<div class="field">
  <%= f.label :author, "Author" %><br />
  <%= f.text_field :author %>
</div>

<div class="field">
  <%= f.label :description, "Description" %><br />
  <%= f.text_area :description %>
</div>

 <div class="field">
  <%= f.label :url, "url" %><br />
  <%= f.text_field :url %>
</div>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/books/show.html.erb
<div class="content">
  <h1><%= @book.title %></h1>
  <h2><%= @book.author %></h2
  <h3><%= @book.description %></h3>
  <h5><%= @book.url %></h5>
</div>

<div>
<%= button_to 'Delete', book_path, method: 'delete', data: { confirm: 'Are you sure?' } %>
</div>

<div class ="reviews">
  <h2>Book reviews from our readers</h2>
</div>
<div class="content">
  <% @book.reviews.order(created_at: :desc).each do |review| %>
  <h3><%= review.review %></h3>
  <h5><%= review.user.role %></h5>
</div>

<div class="button">
  <a href="/books/<%=review.book_id%>/reviews/<%=review.id%>/edit">Edit Review</a>
</div>

<% end %>

<div class="button">
  <a href="/books/<%=@book.id%>/reviews/new">Review Book</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Out Of This World Books</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>


<h3><a href="<%=root_path%>">Out Of This World Books</a></h3>

  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>

<div>
  <p class="navbar-text pull-right">
    <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </p>
</div>

<%= yield %>

</body>
</html>

app/views/reviews/edit.html.erb
<%= form_for @review, :url => { :action => "update" } do |f| %>

<% if @review.errors.any? %>
<div id="error_explanation">
  <h2><%= "#{@review.errors.count} prevented the book from being saved:" %></h2>
  <ul>
    <% @review.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :review, "Review" %><br />
  <%= f.text_area :review, :value => @review.review, :size => "30x10" %>

</div>

<div class="actions">
  <%= f.submit "Edit Review" %>
</div>

<%= button_to 'Delete', book_review_path, method: 'delete', data: { confirm: 'Are you sure?' } %>

<% end %>

app/views/reviews/new.html.erb
<%= form_for([@book, @review]) do |f| %>

<% if @review.errors.any? %>
<div id="error_explanation">
  <h2><%= "#{@review.errors.count} prevented the book from being saved:" %></h2>
  <ul>
    <% @review.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :review, "Review" %><br />
  <%= f.text_area :review %>
</div>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>